# Generated by Django 4.2.6 on 2023-11-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='none.png', upload_to='pizzas/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ingredients', models.ManyToManyField(to='webinterface.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('f_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterface.order')),
                ('f_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterface.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='webinterface.pizzaorder'),
        ),
    ]
