# Generated by Django 4.2.7 on 2023-12-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('protein', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='none.png', upload_to='pizzas/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ingredients', models.ManyToManyField(to='webinterface.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Radio', 'Radio'), ('Check', 'Check'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=15)),
                ('answers', models.ManyToManyField(blank=True, to='webinterface.answer')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order', to='webinterface.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='webinterface.pizza')),
            ],
        ),
    ]
