# Generated by Django 4.2.7 on 2023-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Radio', 'Radio'), ('Check', 'Check'), ('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=15),
        ),
    ]
