# Generated by Django 4.2.6 on 2023-11-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='f_order',
            new_name='forder',
        ),
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='f_pizza',
            new_name='fpizza',
        ),
    ]
