# Generated by Django 4.2.6 on 2023-11-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_rename_f_order_pizzaorder_forder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webinterface.pizzaorder'),
            preserve_default=False,
        ),
    ]
