# Generated by Django 4.2.6 on 2023-11-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0005_rename_forder_pizzaorder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_orders', to='webinterface.order'),
        ),
    ]
