# Generated by Django 4.2.6 on 2023-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_ingredient_carbs_ingredient_fat_ingredient_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='none.png', upload_to='static/pizzas/'),
        ),
    ]
