# Generated by Django 4.2.6 on 2023-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='none.png', upload_to='pizzas/'),
        ),
    ]
