# Generated by Django 4.2.6 on 2023-11-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_remove_order_pizzas_order_pizzas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webinterface.pizzaorder'),
        ),
    ]
