# Generated by Django 4.2.6 on 2023-11-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0004_alter_order_pizzas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='forder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='fpizza',
            new_name='pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
    ]
