# Generated by Django 4.2.6 on 2023-11-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0006_alter_pizzaorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order', to='webinterface.order'),
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ManyToManyField(to='webinterface.pizza'),
        ),
    ]
