# Generated by Django 4.2.6 on 2023-11-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0007_alter_pizzaorder_order_remove_pizzaorder_pizza_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='pizza',
            new_name='pizzas',
        ),
    ]
